/* Generated By:JavaCC: Do not edit this line. LeAnalConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LeAnalConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int RPAREN = 7;
  /** RegularExpression Id. */
  int LPAREN = 8;
  /** RegularExpression Id. */
  int LBRACE = 9;
  /** RegularExpression Id. */
  int RBRACE = 10;
  /** RegularExpression Id. */
  int RBRACKET = 11;
  /** RegularExpression Id. */
  int LBRACKET = 12;
  /** RegularExpression Id. */
  int SEMICOLON = 13;
  /** RegularExpression Id. */
  int COMMA = 14;
  /** RegularExpression Id. */
  int EQUAL = 15;
  /** RegularExpression Id. */
  int MULT = 16;
  /** RegularExpression Id. */
  int MOD = 17;
  /** RegularExpression Id. */
  int DIV = 18;
  /** RegularExpression Id. */
  int PLUS = 19;
  /** RegularExpression Id. */
  int MINUS = 20;
  /** RegularExpression Id. */
  int NOT = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int AND = 23;
  /** RegularExpression Id. */
  int DEQUAL = 24;
  /** RegularExpression Id. */
  int DIF = 25;
  /** RegularExpression Id. */
  int LESS = 26;
  /** RegularExpression Id. */
  int GREATER = 27;
  /** RegularExpression Id. */
  int LEQ = 28;
  /** RegularExpression Id. */
  int GEQ = 29;
  /** RegularExpression Id. */
  int IF = 30;
  /** RegularExpression Id. */
  int ELSE = 31;
  /** RegularExpression Id. */
  int WHILE = 32;
  /** RegularExpression Id. */
  int TYPEDEF = 33;
  /** RegularExpression Id. */
  int INT = 34;
  /** RegularExpression Id. */
  int FLOAT = 35;
  /** RegularExpression Id. */
  int CHAR = 36;
  /** RegularExpression Id. */
  int VOID = 37;
  /** RegularExpression Id. */
  int IDENT = 38;
  /** RegularExpression Id. */
  int LETTER = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<NUMBER>",
    "\")\"",
    "\"(\"",
    "\"{\"",
    "\"}\"",
    "\"]\"",
    "\"[\"",
    "\";\"",
    "\",\"",
    "\"=\"",
    "\"*\"",
    "\"%\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"!\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"typedef\"",
    "\"int\"",
    "\"float\"",
    "\"char\"",
    "\"void\"",
    "<IDENT>",
    "<LETTER>",
  };

}
